export const theme = {
  colors: {
    background: '#F5F3EF',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    popover: '#FFFFFF',
    popoverForeground: '#1A1A1A',
    primary: '#3B82F6',
    primaryForeground: '#FFFFFF',
    primaryLight: '#DBEAFE',
    primaryDark: '#1E40AF',
    secondary: '#F3F4F6',
    secondaryForeground: '#1F2937',
    muted: '#6B7280',
    mutedAlt: '#9CA3AF',
    mutedForeground: '#4B5563',
    accent: '#F3F4F6',
    accentForeground: '#1F2937',
    danger: '#EF4444',
    dangerForeground: '#FFFFFF',
    success: '#10B981',
    successBg: '#D1FAE5',
    successForeground: '#065F46',
    warning: '#F59E0B',
    warningBg: '#FEF3C7',
    warningForeground: '#92400E',
    info: '#3B82F6',
    infoBg: '#DBEAFE',
    infoForeground: '#1E40AF',
    border: '#E5E7EB',
    input: '#F9FAFB',
    ring: '#3B82F6',
    surface: '#FAFAF9',
    surfaceAlt: '#F5F3EF',
    black: '#1A1A1A',
    blackForeground: '#FFFFFF',
  },
  radii: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    '2xl': 28,
    '3xl': 32,
    pill: 9999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  shadows: {
    sm: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.07,
      shadowRadius: 8,
      elevation: 4,
    },
  },
  iconSizes: {
    sm: 20,
    md: 24,
    lg: 28,
  },
} as const;

export type Theme = typeof theme;
