name = "wellness-backend"
main = "src/workers/api-gateway.ts"
compatibility_date = "2024-12-01"

[env.local]
[env.local.vars]
ENVIRONMENT = "local"
JWT_SECRET = "local-jwt-secret-key-for-development-only"
REFRESH_SECRET = "local-refresh-secret-key-for-development-only"
ENCRYPTION_KEY = "local-encryption-key-for-development-only-32chars"
OPENAI_API_KEY = "sk-fake-openai-key-for-local-development"
DEEPGRAM_API_KEY = "fake-deepgram-key-for-local-development"
STRIPE_SECRET_KEY = "sk_test_fake_stripe_key_for_local_development"
STRIPE_WEBHOOK_SECRET = "whsec_fake_webhook_secret_for_local_development"
RESEND_API_KEY = "re_PKoPWqut_6AxmD6spK3hB8JM22TVbdCyc"
FROM_EMAIL= "noreply@qura.co.ke"
ONESIGNAL_APP_ID = "fake-onesignal-app-id-for-local-development"
ONESIGNAL_API_KEY = "fake-onesignal-api-key-for-local-development"
GOOGLE_CLIENT_ID = "fake-google-client-id-for-local-development"
GOOGLE_CLIENT_SECRET = "fake-google-client-secret-for-local-development"
GOOGLE_REDIRECT_URI = "http://localhost:5173/auth/google/callback"
APP_BASE_URL = "http://localhost:5173"
OUTLOOK_CLIENT_ID = "fake-outlook-client-id-for-local-development"
OUTLOOK_CLIENT_SECRET = "fake-outlook-client-secret-for-local-development"

[[env.local.kv_namespaces]]
binding = "CACHE"
id = "wellness_kv_preview"
preview_id = "wellness_kv_preview"

[[env.local.d1_databases]]
binding = "DB"
database_name = "wellness_local"
database_id = "0a0dfcaa-9651-4a32-b131-fd0db7b7b21d"

[[env.local.r2_buckets]]
binding = "ASSETS"
bucket_name = "wellness-r2-local"

[[env.local.queues.producers]]
binding = "TASK_QUEUE"
queue = "wellness-task-queue-local"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "wellness_kv_prod"
preview_id = "wellness_kv_preview"

[[env.production.d1_databases]]
binding = "DB"
database_name = "wellness_prod"
database_id = "d1_prod_id"

[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "wellness-r2-prod"

[[env.production.queues.producers]]
binding = "TASK_QUEUE"
queue = "wellness-task-queue"

[[migrations]]
tag = "v1"
new_classes = ["User", "Task", "HealthLog"]
